[pytest]
pythonpath = .
markers =
    integration: mark test as integration test requiring Ollama service
testpaths = tests
filterwarnings =
    ignore::langchain_core._api.deprecation.LangChainPendingDeprecationWarning
    ignore:.*allowed_objects.*:UserWarning

